# Protocol to use for git operations. Supported values: ssh, https
git_protocol: https

# Editor to use when creating issues, pull requests, etc. Leave blank to use the default editor from the environment.
editor:

# When to display interactive prompts. This is a global configuration and cannot be overridden by hostname.
# Supported values: enabled, disabled
prompt: enabled

# Pager program to use for command output. Example value: less
pager:

# Aliases to define shortcuts for `gh` commands
aliases:
  co: pr checkout
