#!/usr/bin/env bash

# Clear the current image displayed in Kitty terminal using the `icat` kitten.
# Ensure compatibility with the latest Kitty version.

kitty +kitten icat --clear --stdin=no --silent --transfer-mode=file </dev/null >/dev/tty
