indent_type = "Spaces"  # Use spaces for indentation
indent_width = 2        # Set indentation width to 2 spaces
column_width = 120      # Maximum column width
quote_style = "ForceSingle"  # Force the use of single quotes
