# Rich Colors: https://rich.readthedocs.io/en/stable/appendix/colors.html
# Nerd Fonts: https://www.nerdfonts.com/

main:
  # Toggle visibility of the top bars
  show_headers: false

  # Colors for menu and to-do list borders
  body_dim: dim white
  body_highlight: blue

  # Colors for header text
  header_dim: dim white
  header_highlight: blue

  # Welcome message displayed on startup
  welcome_message: |+
    Welcome to Doit! :wave:

  # ASCII art displayed on startup
  ascii_art: |+
    ██████╗  ██████╗  ██████╗ ██╗████████╗
    ██╔══██╗██╔═══██╗██╔═══██╗██║╚══██╔══╝
    ██║  ██║██║   ██║██║   ██║██║   ██║   
    ██║  ██║██║   ██║██║   ██║██║   ██║   
    ██████╔╝╚██████╔╝╚██████╔╝██║   ██║   
    ╚═════╝  ╚═════╝  ╚═════╝ ╚═╝   ╚═╝   

menu:
  # Configuration for the side menu
  icons:
    nested_close: 
    nested_open: ﱮ
    single_topic: 

  theme:
    style_editing: reverse red # Style when editing a menu item
    style_focused: reverse red # Style for the highlighted item
    style_unfocused: white # Style for non-highlighted items

status_bar:
  # Configuration for the bottom status bar
  theme:
    clock: reverse yellow # Style for the clock
    date: reverse green # Style for the date

    # Modes
    insert: cyan
    message: purple1
    normal: blue
    search: magenta
    sort: green

  icons:
    calendar: 
    clock: 

todos:
  icons:
    due_date: 
    todo_completed: 
    todo_overdue: 
    todo_pending: 
    urgency: 

  theme:
    style_editing: bold cyan # Style for the item being edited
    style_focused: bold grey85 # Style for the highlighted to-do item
    style_unfocused: bold grey50 # Style for unhighlighted to-do items

keybindings:
  # Define keybindings for various actions
  # Multiple keybindings are listed as [key1, key2], single as just the character or combo
  # Note: Use 'ctrl+i' for Tab, but "shift+tab" for Shift-Tab
  # Reference: https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode/563480#563480

  move_to_top: [g, home]
  move_to_bottom: [G, end]
  move_down: [j, down]
  shift_down: [J, shift+down]
  move_up: [k, up]
  shift_up: [K, shift+up]
  edit_node: i
  edit_date: d
  toggle_complete: c
  yank_todo: y # Copy the to-do item details
  toggle_expand: z
  toggle_expand_parent: Z
  remove_node: x
  add_sibling: a
  add_child: A
  spawn_sort_menu: ctrl+s
  start_search: /
  select_node: enter
  move_focus_to_menu: h
  show_help: "?"
  increase_urgency: ["+", "="]
  decrease_urgency: ["-", "_"]
